[package]
name = "directrix"
version = "0.1.0"
authors = ["Brandon Grooters <brandon.grooters@bytetrail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.14.0"
gtk = "0.14.0"
cairo-rs = "0.14.0"